%%Region_Analysis 
% Takes the frequency power spectrum (generated by the
% erp_freq_analysis function) of each electrode and averages it into groups
 
load chanlocs2 %loads up the file with each electrode and the region/area they are in
 
dname = 'Y:\Marie Shorrock\NTIP\Auditory Entrainment Study\Frequency';
entrainfiles = dir(fullfile(dname, '*entrain*'));
 
% average across electrodes in each of nReg regions for each file
av_area = [];
 
for f = 1:length(entrainfiles)
    
    entrainname = entrainfiles(f).name;
    [pth nme ext] = fileparts(entrainname);
    C = strsplit(nme,'_');
    basename = strrep(entrainname,'entrain','base');
 
    entrain = load(entrainname); %entrain.f.data
    base = load(basename); % base.fdata
    
    
    av_e = squeeze(mean(entrain.fdata.powspctrm,1)); %avg powspctrm entrain before correction
    av_b = squeeze(mean(base.fdata.powspctrm,1)); %avg powspctrm base 
    av = av_e./av_b; %divides entrainment powerspectrum by baseline as a correction
    
    area = [chanlocs2.area];
    
    uArea = unique(area); %sorts the areas and gets rid of repeats.
    nArea = length(uArea); %find the number of areas 
    
   %need to average the powerspectrum in each area
    for r = 1:nArea
       av_area3(f,r,:) = mean(av(area,uArea(r),:)); %creates a 3D array but we can't copy this into SPSS for stats, therefore it needs to be reduced to be 2D array ==
    end
    
    av_area = permute(av_area,[1 3 2]); %this swaps the second and third one
    av_area = reshape(av_area,[],size(av_area,2)*size(av_area,3)); % columns: freq, regions

    save [C{1} '_' C{2} '_' C{3} '_' C{4} '_area.mat'];
end
